version: '3.9'

services:
  postgres:
    container_name: anomaly-db
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: anomaly
      POSTGRES_USER: MGomed
      POSTGRES_PASSWORD: 1111
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U MGomed -d anomaly"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - anomalydb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  anomalydb-data: