FROM golang:1.21

RUN apt update && apt install -y protobuf-compiler && \
	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && \
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2 && \
	export PATH="$PATH:$(go env GOPATH)/bin"

COPY ./ /build

WORKDIR /build

RUN make generate && make build-server && make build-client